name: build_dbt

on:
  push:
    branches:
      - main
    paths-ignore:
      - adb/**
      - adf/**
      - README.md
  pull_request:
    branches:
      - main
    paths-ignore:
      - adb/**
      - adf/**
      - README.md

env:
  profile: ajc_adb_dbt_all_purpose

jobs:
  dbt_ci:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: install pip dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-databricks sqlfluff-templater-dbt

      - name: verify installation
        run: |
          dbt --version
          sqlfluff --version

      - name: dbt debug
        env:
          adbtoken: ${{ secrets.ADBTOKEN }}      
        run: |
          cd dbt
          dbt debug --profile $profile

      - name: dbt deps
        env:
          adbtoken: ${{ secrets.ADBTOKEN }}      
        run: |
          cd dbt
          dbt deps --profile $profile

      - name: dbt compile
        env:
          adbtoken: ${{ secrets.ADBTOKEN }}   
        run: |
          cd dbt
          dbt compile --profile $profile

      - name: sqlfluff lint
        env:
          adbtoken: ${{ secrets.ADBTOKEN }}     
        run: |
          cd dbt
          sqlfluff lint models/*.sql

      - name: dbt build
        env:
          adbtoken: ${{ secrets.ADBTOKEN }}      
        run: |
          cd dbt
          dbt build --profile $profile
          
      - name: artifact publish
        uses: actions/upload-artifact@v4
        with:
          name: dbt_artifact
          path: |
            dbt/*
            !adf/**
            !adb/**
