name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-dbt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt sqlfluff-templater-dbt

      - name: Verify installation
        run: |
          dbt --version
          sqlfluff --version

      - name: Run sqlfluff lint
        run: |
          sqlfluff lint models/*.sql