name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt sqlfluff-templater-dbt

      - name: Verify installation
        run: |
          dbt --version
          sqlfluff --version

      - name: Publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: models/*.sql  

  check_secrets:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - shell: bash
        env:
          adbtoken: ${{ secrets.ADBTOKEN }}
        run: |
          dbt debug --profile ajc_adb_dbt_all_purpose