name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-dbt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify the Python version you want to use

      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt

      - name: Verify dbt installation
        run: |
          dbt --version

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.2.1-node20
